#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

printf "${YELLOW}🔍 pre-commit 훅을 실행합니다.${NC}\n"

printf "${GREEN}✅ 정상적으로 commit을 완료 하였습니다.${NC}\n"
